# Generated by Django 5.2.17 on 2026-09-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='cotisation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la cotisation mensuelle.', max_digits=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_utilisateurs/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='quota',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quota annuel de remboursement accordé.', max_digits=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
