# Generated by Django 5.2.17 on 2026-09-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utilisateur_cotisation_utilisateur_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='quota',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='cotisation',
            field=models.PositiveIntegerField(default=0, help_text='Montant de la cotisation mensuelle en KMF (sans décimale).'),
        ),
    ]
