# Generated by Django 5.2.17 on 2026-09-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_utilisateur_quota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='cotisation',
        ),
    ]
