# Generated by Django 5.2.17 on 2026-09-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_utilisateur_cotisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numéro joignable, utilisé pour contacter le titulaire du compte.', max_length=20, verbose_name='Téléphone'),
        ),
    ]
