# Generated by Django 5.2.17 on 2026-09-22 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaires', '0001_initial'),
        ('prestataires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordonnance', models.CharField(max_length=100)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('date_emission', models.DateField()),
                ('justificatif', models.FileField(upload_to='justificatifs_prescriptions/')),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_CONTROLE', 'En contrôle'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='SOUMISE', max_length=20)),
                ('motif_signalement', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='beneficiaires.agent')),
                ('ayant_droit', models.ForeignKey(blank=True, help_text="Laisser vide si la prescription concerne l'agent lui-même.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='beneficiaires.ayantdroit')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='prestataires.prestataire')),
                ('soumis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_soumises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_changement', models.DateTimeField(default=django.utils.timezone.now)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['date_changement'],
            },
        ),
    ]
