# Generated by Django 5.2.17 on 2026-09-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='montant_rembourse',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='montant_total',
            field=models.PositiveIntegerField(help_text='Montant en KMF (sans décimale).'),
        ),
    ]
