# Generated by Django 5.2.17 on 2026-09-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0006_naturesoin'),
        ('prescriptions', '0002_alter_prescription_montant_rembourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='nature',
            field=models.ForeignKey(help_text='Type de prestation reçue : consultation, pharmacie, hospitalisation…', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='parametrage.naturesoin', verbose_name='Nature du soin'),
        ),
    ]
