# Generated by Django 5.2.17 on 2026-09-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescription_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='justificatif',
            field=models.FileField(blank=True, help_text="Facultatif en phase de démarrage : les vérifications se font alors manuellement, sur pièce papier, en attendant l'usage officiel de l'application mobile.", upload_to='justificatifs_prescriptions/'),
        ),
    ]
