# Generated by Django 5.2.17 on 2026-10-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_alter_prescription_justificatif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='numero_ordonnance',
            field=models.CharField(blank=True, help_text='Référence interne générée automatiquement à la saisie.', max_length=100),
        ),
    ]
