# Generated by Django 5.2.17 on 2026-09-23 06:44

from django.db import migrations, models


def creer_ligne_unique(apps, schema_editor):
    Parametrage = apps.get_model("parametrage", "Parametrage")
    Parametrage.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_mensuel_defaut', models.PositiveIntegerField(default=0, help_text="Appliqué aux agents et ayants droit qui n'ont pas de quota personnalisé. Montant en KMF, sans décimale.", verbose_name='Quota mensuel par défaut (KMF)')),
                ('age_limite_enfant', models.PositiveSmallIntegerField(default=18, help_text="Un enfant n'est plus couvert à partir de cet âge révolu.", verbose_name="Âge limite de couverture d'un enfant")),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres de la mutuelle',
                'verbose_name_plural': 'Paramètres de la mutuelle',
            },
        ),
        migrations.RunPython(creer_ligne_unique, migrations.RunPython.noop),
    ]
