# Generated by Django 5.2.17 on 2026-09-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrage',
            name='quota_mensuel_defaut',
            field=models.PositiveIntegerField(default=0, help_text='Enveloppe mensuelle partagée entre un agent et ses ayants droit, appliquée aux agents sans quota personnalisé. En KMF, sans décimale.', verbose_name='Quota mensuel par défaut (KMF)'),
        ),
    ]
