# Generated by Django 5.2.17 on 2026-09-23 10:25

from django.db import migrations, models


# Barème communiqué par la mutuelle. Il reste modifiable depuis le back-office :
# ces valeurs ne sont qu'un point de départ.
TRANCHES = [
    (10, "Sans conjoint et sans enfant", "SANS", 0, 0, 21300),
    (20, "Avec conjoint, sans enfant", "AVEC", 0, 0, 25100),
    (30, "1 enfant", "INDIFFERENT", 1, 1, 25100),
    (40, "2 enfants", "INDIFFERENT", 2, 2, 33700),
    (50, "3 à 4 enfants", "INDIFFERENT", 3, 4, 37400),
    (60, "5 enfants et plus", "INDIFFERENT", 5, None, 39300),
]


def creer_bareme(apps, schema_editor):
    TrancheQuota = apps.get_model("parametrage", "TrancheQuota")
    for ordre, libelle, partenaire, mini, maxi, montant in TRANCHES:
        TrancheQuota.objects.create(
            ordre=ordre,
            libelle=libelle,
            partenaire=partenaire,
            enfants_min=mini,
            enfants_max=maxi,
            montant=montant,
        )


def supprimer_bareme(apps, schema_editor):
    apps.get_model("parametrage", "TrancheQuota").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0002_alter_parametrage_quota_mensuel_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrancheQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=10, help_text="Les tranches sont examinées du plus petit au plus grand ; la première qui correspond s'applique.")),
                ('libelle', models.CharField(max_length=120)),
                ('partenaire', models.CharField(choices=[('INDIFFERENT', 'Peu importe'), ('AVEC', 'Avec conjoint'), ('SANS', 'Sans conjoint')], default='INDIFFERENT', max_length=12, verbose_name='Condition sur le conjoint')),
                ('enfants_min', models.PositiveSmallIntegerField(default=0, verbose_name="Nombre d'enfants minimum")),
                ('enfants_max', models.PositiveSmallIntegerField(blank=True, help_text='Laisser vide pour « et plus ».', null=True, verbose_name="Nombre d'enfants maximum")),
                ('montant', models.PositiveIntegerField(verbose_name='Quota mensuel (KMF)')),
            ],
            options={
                'verbose_name': 'Tranche de quota',
                'verbose_name_plural': 'Barème des quotas',
                'ordering': ['ordre', 'enfants_min'],
            },
        ),
        migrations.AddField(
            model_name='parametrage',
            name='conjoints_inclus',
            field=models.PositiveSmallIntegerField(default=1, help_text='Au-delà, chaque conjoint est facturé en supplément.', verbose_name='Conjoints inclus dans la base'),
        ),
        migrations.AddField(
            model_name='parametrage',
            name='cotisation_base',
            field=models.PositiveIntegerField(default=0, help_text='Montant dû par tout agent, couvrant les ayants droit inclus ci-dessous.', verbose_name='Cotisation mensuelle de base (KMF)'),
        ),
        migrations.AddField(
            model_name='parametrage',
            name='cout_conjoint_supplementaire',
            field=models.PositiveIntegerField(default=2000, verbose_name="Coût d'un conjoint supplémentaire (KMF)"),
        ),
        migrations.AddField(
            model_name='parametrage',
            name='cout_enfant_supplementaire',
            field=models.PositiveIntegerField(default=2000, verbose_name="Coût d'un enfant supplémentaire (KMF)"),
        ),
        migrations.AddField(
            model_name='parametrage',
            name='enfants_inclus',
            field=models.PositiveSmallIntegerField(default=3, help_text='Au-delà, chaque enfant est facturé en supplément.', verbose_name='Enfants inclus dans la base'),
        ),
            migrations.RunPython(creer_bareme, supprimer_bareme),
    ]
