# Generated by Django 5.2.17 on 2026-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0003_tranchequota_parametrage_conjoints_inclus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrage',
            name='duree_cycle_mois',
            field=models.PositiveSmallIntegerField(default=1, help_text="Nombre de mois pendant lesquels le quota du barème doit être consommé. À l'échéance, le quota est remis au montant plein : le reliquat non consommé est perdu, il ne se reporte pas.", verbose_name='Durée du cycle de quota (mois)'),
        ),
        migrations.AlterField(
            model_name='tranchequota',
            name='montant',
            field=models.PositiveIntegerField(verbose_name='Quota du cycle (KMF)'),
        ),
    ]
