# Generated by Django 5.2.17 on 2026-09-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0004_parametrage_duree_cycle_mois_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranchequota',
            name='montant',
            field=models.PositiveIntegerField(verbose_name='Quota mensuel (KMF)'),
        ),
    ]
