# Generated by Django 5.2.17 on 2026-09-24 08:18

from django.db import migrations, models

# Liste de départ, établie d'après les prestations couvertes par le réseau
# conventionné. Elle reste modifiable depuis le back-office : ajouter ou
# désactiver une nature ne demande aucune intervention technique.
NATURES = [
    (10, "Consultation"),
    (20, "Pharmacie / médicaments"),
    (30, "Analyse / laboratoire"),
    (40, "Imagerie / radiologie"),
    (50, "Hospitalisation"),
    (60, "Chirurgie"),
    (70, "Maternité"),
    (80, "Soins dentaires"),
    (90, "Optique"),
    (100, "Kinésithérapie"),
    (110, "Évacuation sanitaire"),
    (200, "Autre"),
]


def creer_natures(apps, schema_editor):
    NatureSoin = apps.get_model("parametrage", "NatureSoin")
    for ordre, libelle in NATURES:
        NatureSoin.objects.get_or_create(libelle=libelle, defaults={"ordre": ordre})


def supprimer_natures(apps, schema_editor):
    apps.get_model("parametrage", "NatureSoin").objects.filter(
        libelle__in=[libelle for _, libelle in NATURES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0005_alter_tranchequota_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=10, help_text="Ordre d'affichage dans les listes de saisie.")),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Nature du soin')),
                ('active', models.BooleanField(default=True, help_text='Décocher retire la nature des nouveaux formulaires sans toucher aux prescriptions qui la portent déjà.', verbose_name='Proposée à la saisie')),
            ],
            options={
                'verbose_name': 'Nature de soin',
                'verbose_name_plural': 'Natures de soin',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.RunPython(creer_natures, supprimer_natures),
    ]
