# Generated by Django 5.2.17 on 2026-09-24 08:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0006_naturesoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrage',
            name='fenetre_analyse_jours',
            field=models.PositiveSmallIntegerField(default=30, help_text="Période observée par défaut sur l'écran des anomalies.", verbose_name="Fenêtre d'analyse des anomalies (jours)"),
        ),
        migrations.AddField(
            model_name='parametrage',
            name='seuil_alerte_quota',
            field=models.PositiveSmallIntegerField(default=10, help_text='Un agent est signalé quand il lui reste moins que ce pourcentage de son enveloppe.', verbose_name="Seuil d'alerte sur le quota restant (%)"),
        ),
        migrations.AddField(
            model_name='parametrage',
            name='seuil_volume_ecart_type',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text="Un prestataire est signalé quand son volume dépasse la moyenne du réseau de ce nombre d'écarts-types. Plus la valeur est basse, plus la détection est sensible (et bavarde).", max_digits=4, verbose_name='Sensibilité du volume anormal (écarts-types)'),
        ),
    ]
