# Generated by Django 5.2.17 on 2026-09-24 06:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0002_alter_prescription_montant_rembourse_and_more'),
        ('prestataires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60, verbose_name='N° de facture')),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois facturé')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('date_reception', models.DateField(default=datetime.date.today)),
                ('montant_total_declare', models.PositiveIntegerField(help_text='Total figurant sur la facture ; comparé à la somme réclamée sur les lignes.', verbose_name='Total réclamé à la mutuelle (KMF)')),
                ('fichier', models.FileField(blank=True, upload_to='factures/')),
                ('statut', models.CharField(choices=[('RECUE', 'Reçue'), ('RAPPROCHEE', 'Rapprochée'), ('VALIDEE', 'Validée'), ('CONTESTEE', 'Contestée')], default='RECUE', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='prestataires.prestataire')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_saisies', to=settings.AUTH_USER_MODEL)),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture prestataire',
                'verbose_name_plural': 'Factures prestataires',
                'ordering': ['-annee', '-mois', 'prestataire'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soin', models.DateField()),
                ('matricule', models.CharField(help_text="Matricule de l'agent, tel qu'indiqué sur la facture.", max_length=20)),
                ('nom_beneficiaire', models.CharField(max_length=150)),
                ('nature', models.CharField(max_length=255, verbose_name='Nature du soin')),
                ('montant_soin', models.PositiveIntegerField(help_text='Les 100 % : part agent comprise.', verbose_name='Coût total du soin (KMF)')),
                ('montant_reclame', models.PositiveIntegerField(help_text='La part prise en charge, soit le coût total × taux du prestataire.', verbose_name='Montant réclamé à la mutuelle (KMF)')),
                ('statut', models.CharField(choices=[('A_RAPPROCHER', 'À rapprocher'), ('CONCORDANTE', 'Concordante'), ('ECART_MONTANT', 'Écart de montant'), ('ECART_TAUX', 'Taux mal appliqué'), ('SANS_PRESCRIPTION', 'Aucune prescription déclarée'), ('AGENT_INCONNU', 'Matricule inconnu')], default='A_RAPPROCHER', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['date_soin', 'matricule'],
            },
        ),
        migrations.AddConstraint(
            model_name='facture',
            constraint=models.UniqueConstraint(fields=('prestataire', 'numero'), name='numero_facture_unique_par_prestataire'),
        ),
    ]
