# Generated by Django 5.2.17 on 2026-09-24 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_reception',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
