# Generated by Django 5.2.17 on 2026-09-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_alter_lignefacture_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacture',
            name='statut',
            field=models.CharField(choices=[('A_RAPPROCHER', 'À rapprocher'), ('CONCORDANTE', 'Concordante'), ('ECART_MONTANT', 'Écart de montant'), ('ECART_TAUX', 'Taux mal appliqué'), ('SANS_PRESCRIPTION', 'Aucune prescription déclarée'), ('AGENT_INCONNU', 'Matricule inconnu'), ('NATURE_NON_COUVERTE', 'Nature non couverte par ce prestataire'), ('BENEFICIAIRE_DIFFERENT', 'Bénéficiaire différent de la prescription')], default='A_RAPPROCHER', max_length=30),
        ),
    ]
