# Generated by Django 5.2.17 on 2026-09-22 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('date_embauche', models.DateField()),
                ('plafond_annuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['utilisateur__matricule'],
            },
        ),
        migrations.CreateModel(
            name='AyantDroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('lien_parente', models.CharField(choices=[('CONJOINT', 'Conjoint(e)'), ('ENFANT', 'Enfant'), ('AUTRE', 'Autre')], max_length=20)),
                ('type_justificatif', models.CharField(choices=[('ACTE_MARIAGE', 'Acte de mariage'), ('ACTE_NAISSANCE', 'Acte de naissance'), ('CERTIFICAT_SCOLARITE', 'Certificat de scolarité'), ('AUTRE', 'Autre justificatif')], max_length=30)),
                ('justificatif', models.FileField(upload_to='justificatifs_ayants_droit/')),
                ('date_validite', models.DateField(blank=True, help_text="Laisser vide si le justificatif n'expire pas.", null=True)),
                ('plafond_annuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_verification', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('commentaire_verification', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayants_droit', to='beneficiaires.agent')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ayants_droit_verifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ayant droit',
                'verbose_name_plural': 'Ayants droit',
                'ordering': ['agent', 'nom', 'prenom'],
            },
        ),
    ]
