# Generated by Django 5.2.17 on 2026-09-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayantdroit',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ayantdroit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_ayants_droit/'),
        ),
    ]
