# Generated by Django 5.2.17 on 2026-09-23 06:44

from django.db import migrations, models

QUOTA_HELP_TEXT = (
    "Quota mensuel en KMF (sans décimale). Laisser vide pour appliquer le "
    "quota par défaut défini dans les paramètres de la mutuelle."
)


class Migration(migrations.Migration):
    """Renomme plafond_annuel (décimal, annuel) en quota (entier KMF, mensuel).

    Le renommage préserve les montants déjà saisis ; la conversion en entier
    tronque les centimes, qui n'existent pas en KMF.
    """

    dependencies = [
        ('beneficiaires', '0002_ayantdroit_date_naissance_ayantdroit_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='plafond_annuel',
            new_name='quota',
        ),
        migrations.RenameField(
            model_name='ayantdroit',
            old_name='plafond_annuel',
            new_name='quota',
        ),
        migrations.AlterField(
            model_name='agent',
            name='quota',
            field=models.PositiveIntegerField(blank=True, help_text=QUOTA_HELP_TEXT, null=True),
        ),
        migrations.AlterField(
            model_name='ayantdroit',
            name='quota',
            field=models.PositiveIntegerField(blank=True, help_text=QUOTA_HELP_TEXT, null=True),
        ),
    ]
