# Generated by Django 5.2.17 on 2026-09-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0003_remove_agent_plafond_annuel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayantdroit',
            name='quota',
        ),
        migrations.AlterField(
            model_name='agent',
            name='quota',
            field=models.PositiveIntegerField(blank=True, help_text="Enveloppe mensuelle en KMF (sans décimale) partagée entre l'agent et ses ayants droit. Laisser vide pour appliquer le quota par défaut défini dans les paramètres de la mutuelle.", null=True),
        ),
    ]
