# Generated by Django 5.2.17 on 2026-09-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0004_remove_ayantdroit_quota_alter_agent_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='quota',
        ),
    ]
