# Generated by Django 5.2.17 on 2026-09-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0005_remove_agent_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
