# Generated by Django 5.2.17 on 2026-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0006_alter_agent_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
    ]
