# Generated by Django 5.2.17 on 2026-09-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0007_alter_agent_date_embauche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayantdroit',
            name='lien_parente',
            field=models.CharField(choices=[('CONJOINT', 'Partenaire'), ('ENFANT', 'Enfant'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
