# Generated by Django 5.2.17 on 2026-09-22 16:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('type_prestataire', models.CharField(choices=[('PHARMACIE', 'Pharmacie'), ('ETABLISSEMENT', 'Établissement médical (clinique, hôpital)'), ('PRATICIEN', 'Praticien (médecin, urgentiste)')], max_length=20)),
                ('nom', models.CharField(max_length=150)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('taux_prise_en_charge', models.DecimalField(decimal_places=2, default=80, help_text='Pourcentage prix en charge par la mutuelle (ex. 80 = mutuelle rembourse 80%, agent paie 20%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestataire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestataire conventionné',
                'verbose_name_plural': 'Prestataires conventionnés',
                'ordering': ['code'],
            },
        ),
    ]
