# Generated by Django 5.2.17 on 2026-09-25 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0007_parametrage_fenetre_analyse_jours_and_more'),
        ('prestataires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifPrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_prise_en_charge', models.DecimalField(decimal_places=2, help_text='Pourcentage pris en charge par la mutuelle pour cette nature de soin chez ce prestataire.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nature_soin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='parametrage.naturesoin')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='prestataires.prestataire')),
            ],
            options={
                'verbose_name': 'Tarif par nature de soin',
                'verbose_name_plural': 'Tarifs par nature de soin',
                'ordering': ['nature_soin__ordre'],
                'constraints': [models.UniqueConstraint(fields=('prestataire', 'nature_soin'), name='unique_tarif_prestataire_nature')],
            },
        ),
    ]
