# Generated by Django 5.2.17 on 2026-10-02 08:08

from django.db import migrations, models

# Les anciennes catégories (établissement médical générique, praticien) sont
# remplacées par des types plus précis. Les fiches existantes sont reclassées
# vers l'équivalent le plus proche plutôt que de garder une valeur devenue
# invalide : un établissement médical devient un hôpital (c'était déjà le cas
# du seul exemple en base, un centre hospitalier), un praticien devient un
# dispensaire (structure de soins de proximité la plus comparable). À
# corriger manuellement sur une fiche si le type réel diffère.
RECLASSEMENT = {
    "ETABLISSEMENT": "HOPITAL",
    "PRATICIEN": "DISPENSAIRE",
}


def reclasser_anciens_types(apps, schema_editor):
    Prestataire = apps.get_model("prestataires", "Prestataire")
    for ancien, nouveau in RECLASSEMENT.items():
        Prestataire.objects.filter(type_prestataire=ancien).update(type_prestataire=nouveau)


def restaurer_anciens_types(apps, schema_editor):
    # Non réversible avec certitude (HOPITAL pouvait déjà exister avant la
    # migration) : laissé en no-op plutôt que de deviner.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0002_tarifprestataire'),
    ]

    operations = [
        migrations.RunPython(reclasser_anciens_types, restaurer_anciens_types),
        migrations.AlterField(
            model_name='prestataire',
            name='type_prestataire',
            field=models.CharField(choices=[('HOPITAL', 'Hôpital'), ('DISPENSAIRE', 'Dispensaire'), ('PHARMACIE', 'Pharmacie'), ('CLINIQUE', 'Clinique'), ('IMAGERIE', 'Imagerie'), ('LABORATOIRE', 'Laboratoire')], max_length=20),
        ),
    ]
