# Generated by Django 5.2.17 on 2026-10-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0003_retype_prestataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='type_prestataire',
            field=models.CharField(choices=[('HOPITAL', 'Hôpital'), ('DISPENSAIRE', 'Dispensaire'), ('PHARMACIE', 'Pharmacie'), ('CLINIQUE', 'Clinique'), ('IMAGERIE', 'Imagerie'), ('LABORATOIRE', 'Laboratoire'), ('PRATICIEN', 'Praticien (médecin, urgentiste)')], max_length=20),
        ),
    ]
